@host = http://localhost:8000/api/v1

### Check Code
POST {{host}}/auth-check
Content-Type: application/json

{
    "email": "test08@test.com"
}

### Sign Up or Sign in
POST {{host}}/signup-or-signin
Content-Type: application/json
Authorization: Basic dGVzdDA4QHRlc3QuY29tOjkzNTU3Mg==

### Sign Out
POST {{host}}/signout
Content-Type: application/json

{
    "email": "test08@test.com"
}

### Check Token
GET {{host}}/verify-token
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTIsImVtYWlsIjoidGVzdDA4QHRlc3QuY29tIiwiaWF0IjoxNzA4NjAwMjg5LCJleHAiOjE3MDg2ODY2ODl9.U2FvfFJ1ynIpgMlGjuNW-CScJ7Ucd-onNvmSZ-H0wbI